### ISSUE TITLE
footcoordsの接地判定で力センサ値を座標変換する

### ISSUE THREAD

**Issue by mmurooka** [jsk-ros-pkg/jsk_control#201]
@garaemon

https://github.com/jsk-ros-pkg/jsk_control/blob/master/jsk_footstep_controller/src/footcoords.cpp
の接地判定で，/lfsensor, /rfsensor をそのまま読んでいますが，
力センサ座標系に変換する必要がありそうです．

HRP2とSTAROで力センサの座標系が異なっていました．
（`rostopic echo /lfsensor`で，HRP2は接地時にZ成分が正の値，STAROは接地時にZ成分が負の値になる．）
Rviz上の力センサを表す矢印は，どちらのロボットも正しく出ているのでtfで変換すれば正しくなると思います．

**Comment by garaemon** [comment]
STAROとHRP2の力センサ座標系ってなんだろう? frame教えてもらえる?
おそらく、STAROは

`hoge->fuga->wrench`みたいになんか一個挟まってて、その一つ上が知りたいです. たぶんhogeとfugaが反対を向いているんじゃないかな

**Comment by garaemon** [comment]
STAROの力センサ、回転だけじゃなくて位置も変えてるのか,,, 面倒ですねー

**Comment by mmurooka** [comment]
STAROの足力センサまわりのtfです．
HRP2と同じに見えます，というので合っていますでしょうか．

![image](https://cloud.githubusercontent.com/assets/6636600/5849965/4142e524-a230-11e4-9839-f7ea8730caec.png)

**Comment by garaemon** [comment]
https://github.com/jsk-ros-pkg/jsk_control/issues/202
これで対応しました。
とりあえずlleg_end_coords/rleg_end_coordsと同じ座標系で値を見るようにしましたが、`lfoot_sensor_frame`, `rfoot_sensor_frame`を適切に指定してください

**Comment by garaemon** [comment]
なるほど、このプルリクエストで動くようになると思います

**Comment by snozawa** [comment]
ちなみに接地判定はどういう処理をしていますか？

hrpsys-baseの方でも似たような値を計算してますが、取得できるとよかったりしますでしょうか？

**Comment by garaemon** [comment]
lowpass filterかけて、閾値処理ですね。
取得できると良いですね、という話は以前も出てましたが。

**Comment by garaemon** [comment]
ついでに、ですがhrpsysではエンコーダからルートリンクの速度とかは計算していますか? 
それも欲しいですね

**Comment by mmurooka** [comment]
ありがとうございます．

**Comment by garaemon** [comment]
マージしたので確認してみてください

**Comment by mmurooka** [comment]
```
    pnh.param("lfoot_sensor_frame", lfoot_sensor_frame_, std::string("lleg_end_coords"));
    pnh.param("rfoot_sensor_frame", rfoot_sensor_frame_, std::string("rleg_end_coords"));
```
だと以下のエラーでした．
```
terminate called after throwing an instance of 'tf2::LookupException'
  what():  "lleg_end_coords" passed to lookupTransform argument source_frame does not exist.
[footcoords-28] process has died [pid 15889, exit code -6, cmd /home/leus/ros/hydro/devel/lib/jsk_fo
otstep_controller/footcoords __name:=fo
```

```
    pnh.param("lfoot_sensor_frame", lfoot_sensor_frame_, std::string("lfsensor"));
    pnh.param("rfoot_sensor_frame", rfoot_sensor_frame_, std::string("rfsensor"));
```
では，エラーが出ませんでしたが，座標系が違うままでした．

**Comment by garaemon** [comment]
ふむ、一回目は失敗するのかなぁ、対応するのでちょい待ちです

**Comment by mmurooka** [comment]
あとから，
> rosrun jsk_footstep_controller footcoords

したら，上がって座標も合っていて解決しました．

start_ros_bridgeでいろいろ一緒に上がるなかで，
lleg_end_coords のtfがpublishされる前に，footcoordsが始まってしまうのが問題みたいですね．

**Comment by mmurooka** [comment]
> あとから，
>>   rosrun jsk_footstep_controller footcoords

したら

のときも，
5回に3回くらいは，
```
terminate called after throwing an instance of 'tf2::LookupException'
  what():  "lleg_end_coords" passed to lookupTransform argument source_frame does not exist. 
Aborted (core dumped)
```
で落ちてしまいます．
5回に2回の上がるときは，
```
[ERROR] [1421902329.922831239]: transform error: Lookup would require extrapolation into the future.  Requested time 1421902329.922467916 but the latest data is at time 1421902329.877795528, when looking up transform from frame [lleg_end_coords] to frame [lfsensor]
[ERROR] [1421902329.922878461]: failed to resolve tf of force sensor
```
というエラーが5秒くらい出てその後は出なくなって，正しい接地状態が得られます．

**Comment by garaemon** [comment]
了解です、五分待ってください

✉︎ Ryohei

**Comment by garaemon** [comment]
https://github.com/jsk-ros-pkg/jsk_control/pull/203
これでどうだ?

**Comment by garaemon** [comment]
マージしたので試してみてください。今度こそうまくいくはず

**Comment by mmurooka** [comment]
動きました．ありがとうございました．
