### ISSUE TITLE
Where shold be put packages for eyetracker/psmove-like human machine interaction devices on?

### ISSUE THREAD

**Issue by furushchev** [jsk-ros-pkg/jsk_control#220]
Now in lab, there are several devices working around and codes for them.
I'd like to put the codes on jsk repos and share them.
It is very difficult to me where to put these packages.
Maybe out choice are:
1. make `jsk_control/jsk_devices` directory and put them into this.
2. make another new git repo that is named like `jsk_interfaces`
3-. other ideas

Which is better to do?

**Comment by garaemon** [comment]
I prefer flat filesystem under jsk_control repository.

**Comment by furushchev** [comment]
@garaemon  I'll try to do it! Thank you. :+1:
