### ISSUE TITLE
jsk_control is not released in indigo?

### ISSUE THREAD

**Issue by aginika** [jsk-ros-pkg/jsk_control#225]
I couldn't find jsk_ik_server in apt...
Is there any reason jsk_ik_server and others is released only in hydro?

**Comment by garaemon** [comment]
http://www.ros.org/debbuild/indigo.html

jsk_control is not released to indigo? @k-okada

**Comment by k-okada** [comment]
ok, released, please take care > @aginika

--
◉ Kei Okada

**Comment by aginika** [comment]
Thank you.
