### ISSUE TITLE
footstep_planningの、足裏の抜ける部分

### ISSUE THREAD

**Issue by YuOhara** [jsk-ros-pkg/jsk_control#468]
![screenshot from 2015-09-18 15 53 24](https://cloud.githubusercontent.com/assets/7259700/9953724/3f34b83e-5e1e-11e5-92b2-af1a2292ef3f.png)

pcl_rosの内容かもしれませんが、ロボットの足裏のあたりの平面が延長されて、
その下の本当の平面に足裏があわせられないのですが、どうすればよいでしょうか？

**Comment by garaemon** [comment]
https://github.com/jsk-ros-pkg/jsk_control/blob/master/jsk_footstep_planner/launch/JAXON_RED_footprint.launch

これを良い感じにしてください

**Comment by YutaKojio** [comment]
空中に平面が出てしまう問題は上にあるパラメータをいじることで治りました。
しかし、```odom_cloud```から```laser_self_filter_points```の変換で、
実際に足がつけそうな場所まで抜けてしまいます。
![screenshot from 2015-09-18 22 12 49](https://cloud.githubusercontent.com/assets/11713954/9960963/d91ec84c-5e58-11e5-9277-b6d069f392ee.png)

**Comment by garaemon** [comment]
> しかし、odom_cloudからlaser_self_filter_pointsの変換で、
> 実際に足がつけそうな場所まで抜けてしまいます。

どういうことだろう?

**Comment by YutaKojio** [comment]
１つ前の画像は，白色点群が```odom_cloud```で，```laser_self_filter_points```の出力がピンク色点群なのですが，
laser_self_filter処理後にロボット自身以外の平面まで消えてしまっているため，画像において一歩前に降りるplanningがでなくなってしまいます．
まだコードの中身を読んでいないのですが，
laser_self_filterの処理がlook groundの姿勢ではなくreset-poseの姿勢に対して行われているためではないかと思ったのですが，そういう理解であっていますでしょうか？

**Comment by garaemon** [comment]
laser_self_filterと呼んでるのはpr2_navigation_self_filter? それともrobot-bbox.l?

どちらにせよ、姿勢はきちんと考慮されています。
robot-bbox.lの方は、最近pr2_navigation_self_filterでcolladaサポートしたので、こっちに置き換えられる。
もしbboxの方を使ってたらこちらは直方体近似しているのでもしかしたら何か悪さをしているかも。

シミュレーションなので、ちょっとずるいけどパディングパラメータは0にしちゃってよい。


2015年9月18日金曜日、Yuta Kojio<notifications@github.com>さんは書きました:

> １つ前の画像は，白色点群がodom_cloudで，laser_self_filter_pointsの出力がピンク色点群なのですが，
>
> laser_self_filter処理後にロボット自身以外の平面まで消えてしまっているため，画像において一歩前に降りるplanningがでなくなってしまいます．
> まだコードの中身を読んでいないのですが，
> laser_self_filterの処理がlook
> groundの姿勢ではなくreset-poseの姿勢に対して行われているためではないかと思ったのですが，そういう理解であっていますでしょうか？
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_control/issues/468#issuecomment-141468974>
> .
>


-- 
✉︎ from iPhone

**Comment by YuOhara** [comment]
使ってるのは、attention clipperの方です。

点群処理が遅いので、そのノードに届く際に姿勢が変わってしまっている可能性を先ほどは考えてみました。
急いでいたので省略してしまいましたが、実際にはコードの中を読んで、Syncしているか、あるいは別にsubscribeしてるかで挙動が変わる気がするので、そこはちゃんと見たほうが良さそうです。

**Comment by garaemon** [comment]
どの点群使ってるか忘れてるんだけど、pr2_navigation_self_filterがかかってる点群を使えれば、attention
clipper周りは消せますね。
こっちの方が信頼できるかも。

処理が重いのならうまくpassthroughのパラメータを調整してみるのかな。

2015年9月18日金曜日、Yu Ohara<notifications@github.com>さんは書きました:

> 使ってるのは、attention clipperの方です。
>
> 点群処理が遅いので、そのノードに届く際に姿勢が変わってしまっている可能性を先ほどは考えてみました。
>
> 急いでいたので省略してしまいましたが、実際にはコードの中を読んで、Syncしているか、あるいは別にsubscribeしてるかで挙動が変わる気がするので、そこはちゃんと見たほうが良さそうです。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_control/issues/468#issuecomment-141473276>
> .
>


-- 
✉︎ from iPhone

**Comment by YuOhara** [comment]
will be solved via https://github.com/jsk-ros-pkg/jsk_demos/pull/1065
