### ISSUE TITLE
heightmapのノードが死んでる

### ISSUE THREAD

**Issue by YuOhara** [jsk-ros-pkg/jsk_control#470]
https://github.com/jsk-ros-pkg/jsk_control/blob/master/jsk_footstep_planner/launch/heightmap_perception/heightmap.launch#L67
でtopicの/map_origin_polygon/output_coefficientsにnanの値が入って、
https://github.com/jsk-ros-pkg/jsk_recognition/blob/master/jsk_pcl_ros/src/polygon_points_sampler_nodelet.cpp
が死んでnodelet全体が死んでしまっているのですが、
https://github.com/jsk-ros-pkg/jsk_control/blob/master/jsk_footstep_planner/launch/heightmap_perception/heightmap.launch#L66
でコメントアウトされた部分が正解なのでしょうか？

**Comment by garaemon** [comment]
コメントアウトが正解なきがする

**Comment by YuOhara** [comment]
問題がなければ戻しちゃいます.
変更したらheightmapが出たのは確認済みです。

**Comment by garaemon** [comment]
問題無いです
