### ISSUE TITLE
footstep_visualizer.pyのzmpの座標が間違っている気がする

### ISSUE THREAD

**Issue by garaemon** [jsk-ros-pkg/jsk_control#518]
jaxonだけまちがっているかも

**Comment by garaemon** [comment]
@YutaKojio 
CPが支持多角形の外に出てるのって正しい?

![screenshot from 2015-11-21 19 02 01](https://cloud.githubusercontent.com/assets/40454/11317923/66713cd8-9082-11e5-96af-c2a0c3b31418.png)

**Comment by garaemon** [comment]
rvizでも同様の位置に見えます

**Comment by YutaKojio** [comment]
重心速度が０の時はCPの値は重心位置と等しくなります。
なので、もしロボットが静止している状態で出ているのであれば座標変換がおかしい気がします。

**Comment by garaemon** [comment]
@YutaKojio 膝を曲げているような状態で静止していて、ただ手が少し物に当たっているような姿勢でした。
hrpsysが出しているCPがおかしいのかもしれませｎ

**Comment by garaemon** [comment]
@YutaKojio 
なんかおかしい?
4足歩行時

![screenshot_from_2015-11-24 17 47 12](https://cloud.githubusercontent.com/assets/40454/11361889/a3afb9be-92d3-11e5-9eab-1500a5d43bba.png)

**Comment by YutaKojio** [comment]
> 膝を曲げているような状態で静止していて、ただ手が少し物に当たっているような姿勢でした。

については，set-ref-forceをしている状態でそもそも重心が支持多角形を出ていたらしいのでそれでおかしくはなさそうでした．

> 4足歩行時

については，ちゃんと４足のときにも使えるようになっているか確認します．

**Comment by eisoku9618** [comment]
RootLinkが地面と水平でない場合に表示の方だけうまく行かないようなプログラムになっていたようでした．

CPが可視化されていると，ZMPとCPが可視化されていると，静止時に実際の重心とモデルの重心の差分が見えてとても便利なので，PR出してもらえると助かります > @YutaKojio

**Comment by YutaKojio** [comment]
遅くなりました．
https://github.com/fkanehiro/hrpsys-base/pull/888 で修正しました．
