### ISSUE TITLE
jsk_footstep_plannerでマーカーを動かすと死ぬ

### ISSUE THREAD

**Issue by mttamtam** [jsk-ros-pkg/jsk_control#689]
@YoheiKakiuchi 

rtmlaunch hrpsys_choreonoid_tutorials jaxon_red_choreonoid.launch LOAD_OBJECTS:=true ENVIRONMENT_YAML:=$(rospack find hrpsys_choreonoid_tutorials)/config/terrain.yaml
roslaunch hrpsys_choreonoid_tutorials jaxon_multisense_local.launch
を上げた状態で、
下記のようにフットステッププランナを立ち上げ、ゴール位置のマーカーを動かそうとするとその瞬間にrvizが死にます。

tamura@aconcagua:~/ros/indigo/src/jsk-ros-pkg/jsk_control/jsk_footstep_planner (master)$ roslaunch jsk_footstep_planner JAXON_RED_footstep_planner_perception.launch 
... logging to /home/tamura/.ros/log/f76d7c64-b8b8-11e7-85d3-bc5ff4ea565e/roslaunch-aconcagua-20301.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://aconcagua:43194/

SUMMARY
========

CLEAR PARAMETERS
 * /joy_manager/

PARAMETERS
 * /footstep_marker/default_footstep_margin: 0.2
 * /footstep_marker/disable_tf: False
 * /footstep_marker/footstep_size_x: 0.237418
 * /footstep_marker/footstep_size_y: 0.134017
 * /footstep_marker/frame_id: map
 * /footstep_marker/lleg_footstep_offset: [0.015502, 0.0100...
 * /footstep_marker/rleg_footstep_offset: [0.015502, -0.010...
 * /footstep_marker/use_default_step_as_goal: True
 * /footstep_planner/collision_bbox_offset: [0, 0, 0.8]
 * /footstep_planner/collision_bbox_size: [0.35, 0.65, 0.65]
 * /footstep_planner/default_lfoot_to_rfoot_offset: [0, -0.2, 0]
 * /footstep_planner/footstep_size_x: 0.26
 * /footstep_planner/footstep_size_y: 0.135
 * /footstep_planner/lleg_footstep_offset: [0.015, 0.0, 0.0]
 * /footstep_planner/local_move_theta: 0.1
 * /footstep_planner/local_move_theta_num: 0
 * /footstep_planner/local_move_theta_offset: 0.0
 * /footstep_planner/local_move_x: 0.02
 * /footstep_planner/local_move_x_num: 1
 * /footstep_planner/local_move_x_offset: 0.14
 * /footstep_planner/local_move_y: 0.01
 * /footstep_planner/local_move_y_num: 0
 * /footstep_planner/local_move_y_offset: 0.0
 * /footstep_planner/obstacle_resolution: 0.1
 * /footstep_planner/plane_estimation_max_iterations: 200
 * /footstep_planner/plane_estimation_min_inliers: 100
 * /footstep_planner/plane_estimation_min_ratio_of_inliers: 0.8
 * /footstep_planner/plane_estimation_normal_distance_weight: 0.2
 * /footstep_planner/plane_estimation_normal_opening_angle: 0.2
 * /footstep_planner/plane_estimation_outlier_threshold: 0.024
 * /footstep_planner/plane_estimation_use_normal: False
 * /footstep_planner/project_goal_state: True
 * /footstep_planner/project_start_state: True
 * /footstep_planner/rleg_footstep_offset: [0.015, 0.0, 0.0]
 * /footstep_planner/skip_cropping: False
 * /footstep_planner/successors: [{'y': 0, 'x': 0,...
 * /footstep_planner/support_check_vertex_neighbor_threshold: 0.02
 * /footstep_planner/support_check_x_sampling: 3
 * /footstep_planner/support_check_y_sampling: 3
 * /footstep_planner/support_padding_x: 0.0
 * /footstep_planner/support_padding_y: 0.0
 * /footstep_planner/transition_limit_pitch: 0.6
 * /footstep_planner/transition_limit_roll: 0.6
 * /footstep_planner/transition_limit_x: 0.5
 * /footstep_planner/transition_limit_y: 0.35
 * /footstep_planner/transition_limit_yaw: 0.4
 * /footstep_planner/transition_limit_z: 0.4
 * /footstep_planner/use_lazy_perception: False
 * /footstep_planner/use_local_movement: True
 * /footstep_planner/use_obstacle_model: True
 * /footstep_planner/use_pointcloud_model: True
 * /footstep_planner/use_transision_limit: False
 * /go_pos_server/force_replanning: False
 * /go_pos_server/plane_projection: False
 * /jaxon_footstep_controller/plane_projection: False
 * /jaxon_footstep_controller/use_step_refine: True
 * /joy_driver/autorepeat_rate: 50
 * /joy_driver/coalesce_interval: 0.01
 * /joy_driver/deadzone: 0.2
 * /joy_driver/dev: /dev/input/js0
 * /joy_manager/controller_type: auto
 * /joy_manager/plugins/FootstepMarker/args/frame_id: map
 * /joy_manager/plugins/FootstepMarker/args/set_pose: set_pose
 * /joy_manager/plugins/FootstepMarker/args/sync_rate: 1.0
 * /joy_manager/plugins/FootstepMarker/args/use_tf: False
 * /joy_manager/plugins/FootstepMarker/class: JoyFootstepMarker
 * /laser_origin_cloud/target_frame_id: head_root
 * /octomap_server/frame_id: map
 * /octomap_server/resolution: 0.1
 * /octomap_server/sensor_model/hit: 0.6
 * /octomap_server/sensor_model/max_range: 5.0
 * /octomap_server/sensor_model/miss: 0.4
 * /rosdistro: indigo
 * /rosversion: 1.11.21

NODES
  /
    footstep_marker (jsk_footstep_planner/footstep_marker)
    footstep_planner (jsk_footstep_planner/footstep_planner_node)
    go_pos_server (roseus/roseus)
    jaxon_footstep_controller (jsk_footstep_controller/jaxon-footstep-controller.l)
    joy_driver (joy/joy_node)
    joy_manager (jsk_teleop_joy/joy.py)
    laser_origin_cloud (jsk_pcl_ros/tf_transform_cloud)
    octomap_server (octomap_server/octomap_server_node)
    rviz (rviz/rviz)

ROS_MASTER_URI=http://localhost:11311

core service [/rosout] found
process[laser_origin_cloud-1]: started with pid [20336]
process[octomap_server-2]: started with pid [20412]
process[footstep_planner-3]: started with pid [20413]
process[footstep_marker-4]: started with pid [20414]
process[jaxon_footstep_controller-5]: started with pid [20420]
process[joy_driver-6]: started with pid [20442]
process[joy_manager-7]: started with pid [20458]
process[go_pos_server-8]: started with pid [20502]
[ERROR] [1508849280.391697484]: Couldn't open joystick /dev/input/js0. Will retry every second.
process[rviz-9]: started with pid [20514]
configuring by "/home/tamura/ros/indigo_parent/devel/share/euslisp/jskeus/eus//lib/eusrt.l"
;; readmacro ;; object ;; packsym ;; common ;; constants ;; stream ;; string ;; loader ;; pprint ;; process ;; hashtab ;; array ;; mathtran ;; eusdebug ;; eusforeign ;; coordinates ;; tty ;; history ;; toplevel ;; trans ;; comp ;; builtins ;; par ;; intersection ;; geoclasses ;; geopack ;; geobody ;; primt ;; compose ;; polygon ;; viewing ;; viewport ;; viewsurface ;; hid ;; shadow ;; bodyrel ;; dda ;; helpsub ;; eushelp ;; xforeign ;; Xdecl ;; Xgraphics ;; Xcolor ;; Xeus ;; Xevent ;; Xpanel ;; Xitem ;; Xtext ;; Xmenu ;; Xscroll ;; Xcanvas ;; Xtop ;; Xapplwin 
connected to Xserver DISPLAY=:0
configuring by "/home/tamura/ros/indigo_parent/devel/share/euslisp/jskeus/eus//lib/eusrt.l"
;; readmacro ;; object ;; packsym ;; common X events are being asynchronously monitored.
;; constants ;; pixword ;; RGBHLS ;; convolve ;; piximage ;; stream ;; string ;; loader ;; pprint ;; process ;; hashtab ;; array ;; pbmfile ;; image_correlation ;; oglforeign ;; mathtran ;; eusdebug ;; eusforeign ;; coordinates ;; tty ;; gldecl ;; history ;; toplevel ;; glconst ;; trans ;; comp ;; builtins ;; par ;; intersection ;; geoclasses ;; glforeign ;; gluconst ;; geopack ;; geobody ;; primt ;; compose ;; polygon ;; viewing ;; viewport ;; gluforeign ;; glxconst ;; glxforeign ;; eglforeign ;; eglfunc ;; glutil ;; gltexture ;; viewsurface ;; glprim ;; gleus ;; glview ;; hid ;; shadow ;; toiv-undefined ;; fstringdouble ;; bodyrel ;; dda irtmath irtutil ;; helpsub ;; eushelp ;; xforeign ;; Xdecl irtc irtgeoc irtgraph ;; Xgraphics ;; Xcolor ;; Xeus pgsql ;; Xevent ;; Xpanel ;; Xitem ;; Xtext ;; Xmenu ;; Xscroll ;; Xcanvas ;; Xtop irtgeo ;; Xapplwin euspqp pqp irtscene irtmodel 
connected to Xserver DISPLAY=:0
irtdyna X events are being asynchronously monitored.
;; pixword ;; RGBHLS ;; convolve ;; piximage irtrobot irtsensor irtbvh ;; pbmfile ;; image_correlation ;; oglforeign ;; gldecl irtcollada irtpointcloud ;; glconst irtx eusjpeg euspng png irtimage irtglrgb 
;; extending gcstack 0x56a1ad0[16374] --> 0x5b00810[32748] top=3d44
;; glforeign ;; gluconst ;; gluforeign ;; glxconst ;; glxforeign ;; eglforeign ;; eglfunc ;; glutil ;; gltexture ;; glprim ;; gleus ;; glview ;; toiv-undefined ;; fstringdouble irtmath irtutil irtc irtgeoc irtgraph pgsql irtgl irtgeo euspqp pqp irtscene irtmodel irtglc irtviewer 
EusLisp 9.22(821db23 1.0.12) for Linux64 created on aconcagua(Fri Sep 22 22:26:54 JST 2017)
irtdyna irtrobot irtsensor irtbvh roseus irtcollada ;; loading roseus("1.6.2-2-g7a769a4") on euslisp((9.22 aconcagua Fri Sep 22 22:26:54 JST 2017 821db23 1.0.12))
[ INFO] [1508849280.725934743]: install ros::roseus-sigint-handler
irtpointcloud eustf irtx eusjpeg euspng png irtimage irtglrgb 
;; extending gcstack 0x57b6ad0[16374] --> 0x5c15810[32748] top=3d44
irtgl irtglc irtviewer 
EusLisp 9.22(821db23 1.0.12) for Linux64 created on aconcagua(Fri Sep 22 22:26:54 JST 2017)
roseus ;; loading roseus("1.6.2-2-g7a769a4") on euslisp((9.22 aconcagua Fri Sep 22 22:26:54 JST 2017 821db23 1.0.12))
[ INFO] [1508849280.778038151]: install ros::roseus-sigint-handler
eustf roseus_c_util roseus_c_util [ INFO] [1508849281.068950614, 62.667000000]: 24 successors are defined
[ INFO] [1508849281.069014638, 62.667000000]: default_offset: #f(0.000000 -0.200000 0.000000)
[ INFO] [1508849281.069032135, 62.667000000]: left_leg_offset: #f(0.015000 0.000000 0.000000)
[ INFO] [1508849281.069044041, 62.667000000]: right_leg_offset: #f(0.015000 0.000000 0.000000)
[ INFO] [1508849281.069054982, 62.667000000]: successor_00: (make-coords :pos (scale 1000 #f(0.000000 -0.200000 0)) :rpy (list 0.000000 0 0))
[ INFO] [1508849281.069062743, 62.667000000]: successor_01: (make-coords :pos (scale 1000 #f(0.000000 -0.300000 0)) :rpy (list 0.000000 0 0))
[ INFO] [1508849281.069070385, 62.667000000]: successor_02: (make-coords :pos (scale 1000 #f(0.000000 -0.240000 0)) :rpy (list 0.000000 0 0))
[ INFO] [1508849281.069077778, 62.667000000]: successor_03: (make-coords :pos (scale 1000 #f(0.000000 -0.140000 0)) :rpy (list 0.000000 0 0))
[ INFO] [1508849281.069084762, 62.667000000]: successor_04: (make-coords :pos (scale 1000 #f(0.000000 -0.180000 0)) :rpy (list 0.000000 0 0))
[ INFO] [1508849281.069091868, 62.667000000]: successor_05: (make-coords :pos (scale 1000 #f(0.160000 -0.200000 0)) :rpy (list 0.000000 0 0))
[ INFO] [1508849281.069099044, 62.667000000]: successor_06: (make-coords :pos (scale 1000 #f(0.100000 -0.200000 0)) :rpy (list 0.000000 0 0))
[ INFO] [1508849281.069107770, 62.667000000]: successor_07: (make-coords :pos (scale 1000 #f(0.020000 -0.200000 0)) :rpy (list 0.000000 0 0))
[ INFO] [1508849281.069114689, 62.667000000]: successor_08: (make-coords :pos (scale 1000 #f(0.130000 -0.200000 0)) :rpy (list 0.000000 0 0))
[ INFO] [1508849281.069121440, 62.667000000]: successor_09: (make-coords :pos (scale 1000 #f(0.070000 -0.200000 0)) :rpy (list 0.000000 0 0))
[ INFO] [1508849281.069128335, 62.667000000]: successor_10: (make-coords :pos (scale 1000 #f(-0.100000 -0.200000 0)) :rpy (list 0.000000 0 0))
[ INFO] [1508849281.069135343, 62.667000000]: successor_11: (make-coords :pos (scale 1000 #f(-0.040000 -0.200000 0)) :rpy (list 0.000000 0 0))
[ INFO] [1508849281.069143050, 62.667000000]: successor_12: (make-coords :pos (scale 1000 #f(-0.000147 -0.197907 0)) :rpy (list 0.140000 0 0))
[ INFO] [1508849281.069151487, 62.667000000]: successor_13: (make-coords :pos (scale 1000 #f(-0.000019 -0.199250 0)) :rpy (list 0.050000 0 0))
[ INFO] [1508849281.069158740, 62.667000000]: successor_14: (make-coords :pos (scale 1000 #f(-0.000270 -0.257167 0)) :rpy (list 0.190000 0 0))
[ INFO] [1508849281.069165900, 62.667000000]: successor_15: (make-coords :pos (scale 1000 #f(0.099853 -0.197907 0)) :rpy (list 0.140000 0 0))
[ INFO] [1508849281.069173064, 62.667000000]: successor_16: (make-coords :pos (scale 1000 #f(0.039939 -0.198652 0)) :rpy (list 0.090000 0 0))
[ INFO] [1508849281.069180208, 62.667000000]: successor_17: (make-coords :pos (scale 1000 #f(-0.000147 -0.202093 0)) :rpy (list -0.140000 0 0))
[ INFO] [1508849281.069187467, 62.667000000]: successor_18: (make-coords :pos (scale 1000 #f(-0.000019 -0.200750 0)) :rpy (list -0.050000 0 0))
[ INFO] [1508849281.069194137, 62.667000000]: successor_19: (make-coords :pos (scale 1000 #f(-0.000270 -0.262833 0)) :rpy (list -0.190000 0 0))
[ INFO] [1508849281.069200815, 62.667000000]: successor_20: (make-coords :pos (scale 1000 #f(0.099853 -0.202093 0)) :rpy (list -0.140000 0 0))
[ INFO] [1508849281.069208704, 62.667000000]: successor_21: (make-coords :pos (scale 1000 #f(0.039939 -0.201348 0)) :rpy (list -0.090000 0 0))
[ INFO] [1508849281.069215291, 62.667000000]: successor_22: (make-coords :pos (scale 1000 #f(-0.040061 -0.198652 0)) :rpy (list 0.090000 0 0))
[ INFO] [1508849281.069221948, 62.667000000]: successor_23: (make-coords :pos (scale 1000 #f(-0.040061 -0.201348 0)) :rpy (list -0.090000 0 0))
[ INFO] [1508849281.069233560, 62.667000000]: building graph
[ INFO] [1508849281.069292664, 62.667000000]: build graph done
[ INFO] [1508849281.085201686, 62.668000000]: waiting for /footstep_planner/collision_bounding_box_info
[ INFO] [1508849281.195138878, 62.683000000]: reset marker
[ INFO] [1508849282.336336545, 62.885000000]: initialization done
/home/tamura/ros/indigo/src/jsk-ros-pkg/jsk_control/jsk_teleop_joy/src/jsk_teleop_joy/joy.py:78: SyntaxWarning: The publisher should be created with an explicit keyword argument 'queue_size'. Please see http://wiki.ros.org/rospy/Overview/Publishers%20and%20Subscribers for more information.
  self.menu_pub = rospy.Publisher("/overlay_menu", OverlayMenu)

;; extending gcstack 0x5b00810[32738] --> 0x68753f0[65476] top=7e23

;; extending gcstack 0x5c15810[32738] --> 0x65ee8a0[65476] top=7da7
[ERROR] [1508849285.357877570]: unknown ros::param::get, key=~/replanning_translation_threshold
[ INFO] [1508849290.195763432, 64.614000000]: GoPos Server is ready as /go_pos_server
[ WARN] [1508849308.181621766, 70.649000000]: Waiting for actionlib interface forever because controler-timeout is nil
";; Add controllers"
[ WARN] [1508849308.853719149, 70.883000000]: Waiting for actionlib interface forever because controler-timeout is nil
[ WARN] [1508849309.109995310, 70.989000000]: Waiting for actionlib interface forever because controler-timeout is nil
[ WARN] [1508849309.419644414, 71.099000000]: Waiting for actionlib interface forever because controler-timeout is nil
[ WARN] [1508849309.730787284, 71.205000000]: Waiting for actionlib interface forever because controler-timeout is nil
[ WARN] [1508849310.008544057, 71.311000000]: Waiting for actionlib interface forever because controler-timeout is nil
[ WARN] [1508849310.324475710, 71.415000000]: Waiting for actionlib interface forever because controler-timeout is nil
";; Add hands"
[ WARN] [1508849310.861015899, 71.619000000]: ROSEUS is already installed as /jaxon_footstep_controller
[ WARN] [1508849319.027877012, 74.749000000]: [/thk_hand_right] action server is not found
[ WARN] [1508849319.027951495, 74.749000000]:      goal=0, cancel=0, feedback=0, result=0
[ WARN] [1508849319.028024595, 74.749000000]: #<ros::simple-action-client #X11bd1bf8 /thk_hand_right> is not respond, pr2-interface is disabled
[ WARN] [1508849319.028062092, 74.749000000]: #<ros::simple-action-client #X11bcfdc8 /thk_hand_left> is not respond, pr2-interface is disabled
[ WARN] [1508849319.280046843, 74.830000000]: ROSEUS is already installed as /jaxon_footstep_controller
[ INFO] [1508849324.929754962, 76.619000000]: simple footstep controller is ready as /jaxon_footstep_controller
[ INFO] [1508849357.002083847, 89.037000000]: pose_up
[ INFO] [1508849357.002120771, 89.037000000]: start planning
[ INFO] [1508849357.004987445, 89.042000000]: planCB
[ INFO] [1508849357.005400394, 89.042000000]: start_solver timeout: 10.000000
[ INFO] [1508849357.005606761, 89.042000000]: Took 0.000080 sec
Perception took 0.000000 sec
Planning took 0.000080 sec
1 path
open list: 0
close list:0
[ INFO] [1508849357.005649258, 89.042000000]: use_obstacle_model: 1
Qt has caught an exception thrown from an event handler. Throwing
exceptions from an event handler is not supported in Qt. You must
reimplement QApplication::notify() and catch all exceptions there.

terminate called after throwing an instance of 'Ogre::Exception'
  what():  OGRE EXCEPTION(5:): Could not find font Arial in MovableText::setFontName
[ WARN] [1508849357.099110094, 89.067000000]: [footstep_planner] action-result-cb may recieved old client's goal
[ WARN] [1508849357.099157438, 89.067000000]:      expected goal id nil
[ WARN] [1508849357.099180764, 89.067000000]:      recieved goal id /footstep_marker-3-89.42000000
[rviz-9] process has died [pid 20514, exit code -6, cmd /opt/ros/indigo/lib/rviz/rviz -d /home/tamura/ros/indigo/src/jsk-ros-pkg/jsk_control/jsk_footstep_planner/config/jaxon_footstep_planner_perception.rviz __name:=rviz __log:=/home/tamura/.ros/log/f76d7c64-b8b8-11e7-85d3-bc5ff4ea565e/rviz-9.log].
log file: /home/tamura/.ros/log/f76d7c64-b8b8-11e7-85d3-bc5ff4ea565e/rviz-9*.log

**Comment by k-okada** [comment]
使っているjsk_rviz_plugins のバージョンはなんですか？
https://github.com/jsk-ros-pkg/jsk_visualization/pull/676
かな，とおもいました．

**Comment by mttamtam** [comment]
遅くなりすいません。
岡田先生のご指摘のとおりで、
```
tamura@aconcagua:~/ros/indigo/src/jsk-ros-pkg/jsk_visualization/jsk_rviz_plugins (master)$ git log
commit 30ee668e47af175057548041802d9846c65918c9
Merge: a1a5ab2 997c218
Author: Kei Okada <k-okada@jsk.t.u-tokyo.ac.jp>
Date:   Wed Oct 12 01:39:16 2016 +0900

    Merge pull request #643 from mmurooka/empty-service-panel-unused-varialbe
    
    [jsk_rviz_plugins/src/empty_service_call_interface.cpp ] remove unused variables.
```
だったのでjsk_rviz_pluginsが１年前ぐらいだったのを最新版にしたら問題なく動きました。
ありがとうございました。

**Comment by k-okada** [comment]
良かったです．
手元にソースツリー持つとこういうことがおこって，じゃあ常にwstool
updateしたらいいかというと，regressionも心配だし，ということで，自分でいじることがなければdebを使っておくのがいいですね．
ということで，リリースしました．週明けには使えると思います．
https://github.com/ros/rosdistro/pull/16173

--
◉ Kei Okada


2017-10-26 20:01 GMT+09:00 Juntaro Tamura <notifications@github.com>:
