### ISSUE TITLE
release request for melodic

### ISSUE THREAD

**Issue by knorth55** [jsk-ros-pkg/jsk_control#759]
`jsk_ik_server` is needed for `drc_task_common` in `jsk_demos`, which is not released in melodic.
in order to build `jsk_demos`, we need to build `jsk_control` from source now...

**Comment by k-okada** [comment]
done -> https://github.com/ros/rosdistro/pull/27716
--
◉ Kei Okada



2020年12月10日(木) 12:54 Shingo Kitagawa <notifications@github.com>:

**Comment by knorth55** [comment]
Thank you!
